# Generated by Django 4.1.3 on 2022-11-17 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('description', models.TextField()),
                ('is_feature', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('published', 'published'), ('unpublished', 'unpublished'), ('postponed', 'postponed'), ('archived', 'archived')], default='published', max_length=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_category', to='category.category')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
                'db_table': 'db_product',
                'ordering': ('status', '-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to=product.utils.product_photo_directory_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product')),
            ],
        ),
    ]
