# Generated by Django 3.2 on 2022-11-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Image',
            new_name='image',
        ),
    ]
