# Generated by Django 3.2 on 2022-11-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_operator',
            new_name='is_operator',
        ),
    ]
